<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>


    <h2 id="output"></h2>
    

    <script>
        const fakeFetch = (url) => {
	return new Promise((resolve, reject) => {
	  setTimeout(() => {
	    if (url === "https://example.com/api/data") {
	      reject({
	        status: 500,
	        message: "Internal Server Error"
	      });
	    } else {
	      resolve({
	        status: 200,
	        data: {
	          message: "Success"
	        }
	      });
	    }
	  }, 2000);
	});
};

// Your Code here

const output = document.querySelector('#output');

fakeFetch('https://example.com/api/data')
.then((res) => {
    console.log(res)
})
.catch((error) => {
    if(error.status === 500){

        output.innerHTML = error.message + "  The server crashed. Please try again in some time. ";
    }
})


// Output on the DOM should be: 
// Internal Server Error! The server crashed. Please try again in some time.
    </script>
</body>
</html>